export const maindata = [
    {
        id:1,
        category:'maindata',
        title:"[Kim's butcher] 호주산 소고기 샤브샤브 500g(냉동)",
        imgsrc:'/maindata/section1img1.jpg',
        originPrice:14900,
        salePer:19,
        Comment:'9,999+',
        Coupon:true,
        Coupon2:false,
    },
    {
        id:2,
        category:'maindata',
        title:"김치듬뿍 한돈 제육볶음",
        imgsrc:'/maindata/section1img2.jpg',
        originPrice:12900,
        salePer:10,
        Comment:'250',
        Coupon:false,
        Coupon2:true,
    },
    {
        id:3,
        category:'maindata',
        title:"[KF365] 에어프라이어용 생선까스 (리뉴얼)",
        imgsrc:'/maindata/section1img3.jpg',
        originPrice:13500,
        salePer:26,
        Comment:'999+',
        Coupon:false,
        Coupon2:true,
    },
    {
        id:4,
        category:'maindata',
        title:"[KF365] 한돈 부위별 대용량 가성비 7종",
        imgsrc:'/maindata/section1img4.jpg',
        originPrice:28900,
        salePer:34,
        Comment:'9,999+',
        Coupon:false,
        Coupon2:false,
    },
    {
        id:5,
        category:'maindata',
        title:"[홍익궁중전통] 육개장 (2인분)",
        imgsrc:'/maindata/section1img5.jpg',
        originPrice:10800,
        salePer:20,
        Comment:'9,999+',
        Coupon:false,
        Coupon2:true,
    },
    {
        id:6,
        category:'maindata',
        title:"코카콜라 제로 1.5L",
        imgsrc:'/maindata/section1img6.jpg',
        originPrice:3180,
        salePer:37,
        Comment:'999+',
        Coupon:false,
        Coupon2:false,
    },
    {
        id:7,
        category:'maindata',
        title:"[KF365] 서울식 소불고기 600g(냉동)",
        imgsrc:'/maindata/section1img7.jpg',
        originPrice:14000,
        salePer:15,
        Comment:'999+',
        Coupon:false,
        Coupon2:true,
    },
    {
        id:8,
        category:'maindata',
        title:"[바름] 영암 친환경 꿀고구마 1.5kg",
        imgsrc:'/maindata/section1img8.jpg',
        originPrice:8990,
        salePer:15,
        Comment:'9,999+',
        Coupon:false,
        Coupon2:true,
    },
    {
        id:9,
        category:'maindata',
        title:"[KF365] 간편한 6가지 해물 모듬",
        imgsrc:'/maindata/section1img9.jpg',
        originPrice:8900,
        salePer:7,
        Comment:'9,999+',
        Coupon:false,
        Coupon2:false,
    },
    {
        id:10,
        category:'maindata',
        title:"코카콜라 제로 (250mL X 6캔)",
        imgsrc:'/maindata/section1img10.jpg',
        originPrice:7580,
        salePer:30,
        Comment:'9,999+',
        Coupon:false,
        Coupon2:false,
    },
    {
        id:11,
        category:'maindata',
        title:"[KF365] 훈제오리 2종 (2입)",
        imgsrc:'/maindata/section1img11.jpg',
        originPrice:10500,
        salePer:33,
        Comment:'9,999+',
        Coupon:false,
        Coupon2:false,
    },
    {
        id:12,
        category:'maindata',
        title:"[고메공방] 계란빵 2종 (5개입) (택1)",
        imgsrc:'/maindata/section1img12.jpg',
        originPrice:12500,
        salePer:12,
        Comment:'999+',
        Coupon:false,
        Coupon2:false,
    },
    {
        id:13,
        category:'maindata',
        title:"[압구정주꾸미] 주꾸미 볶음 2종 (택1)",
        imgsrc:'/maindata/section1img13.jpg',
        originPrice:8900,
        salePer:15,
        Comment:'9,999+',
        Coupon:false,
        Coupon2:false,
    },
    {
        id:14,
        category:'maindata',
        title:"[어반다이닝] 바지락 술찜 파스타",
        imgsrc:'/maindata/section1img14.jpg',
        originPrice:12900,
        salePer:11,
        Comment:'999+',
        Coupon:false,
        Coupon2:false,
    },
    {
        id:15,
        category:'maindata',
        title:"[매일] 바이오 요거트 파르페 아이스크림 220mL X 4개입",
        imgsrc:'/maindata/section1img15.jpg',
        originPrice:14000,
        salePer:15,
        Comment:'215+',
        Coupon:false,
        Coupon2:false,
    },
    {
        id:16,
        category:'maindata',
        title:"[투다리] 인기 밀키트 4종 골라담기 (택1)",
        imgsrc:'/maindata/section1img16.jpg',
        originPrice:14900,
        salePer:16,
        Comment:'9,999+',
        Coupon:false,
        Coupon2:false,
    }
]

export const LowPrice = [
    {
        id:1,
        category:'lowprice',
        descript: "20% 단독쿠폰!! 세계 최초 100% 트라이탄 밀폐용기",
        title:"[고트만] 1+1 크리스탈락 트라이탄 밀폐용기",
        imgsrc:'/maindata/lowPrice.jpg',
        originPrice:32000,
        salePer:33,
        Comment:'168',
        Coupon:true,
        Coupon2:false
    },
]

export const mainranking = [
    {
        id:1,
        category:'mainranking',
        title:"[KF365] 1+ 한우 국거리 300g(냉장)",
        imgsrc:'/maindata_ranking/ranking1.jpg',
        TotalPrice:12720,
        salePer:20,
        MembersCoupon:false,
        Coupon2:true,
    },
    {
        id:2,
        category:'mainranking',
        title:"[정지선의 티엔미미] 티엔미미 인기 면요리 4종 (택1)",
        imgsrc:'/maindata_ranking/ranking2.jpg',
        TotalPrice:5925,
        salePer:25,
        MembersCoupon:true,
        Coupon2:true,
    },
    {
        id:3,
        category:'mainranking',
        title:"[오봉집] 낙지볶음 2종(냉동)",
        imgsrc:'/maindata_ranking/ranking3.jpg',
        TotalPrice:6990,
        salePer:12,
        MembersCoupon:false,
        Coupon2:false,
    },
    {
        id:4,
        category:'mainranking',
        title:"[이연복의 목란] 짜장면 2인분",
        imgsrc:'/maindata_ranking/ranking4.jpg',
        TotalPrice:7984,
        salePer:20,
        MembersCoupon:true,
        Coupon2:true,
    },
    {
        id:5,
        category:'mainranking',
        title:"[자연실록] 닭가슴살 큐브스테이크 4종",
        imgsrc:'/maindata_ranking/ranking4.jpg',
        TotalPrice:6650,
        salePer:30,
        MembersCoupon:true,
        Coupon2:true,
    },
]